VDE_SRC := src/vde/vde_init_mem.sv src/vde/vde.sv 
VDE_SRC += src/vde/vde_map_emitter.sv src/vde/vde_color_emitter.sv
VDE_SRC += src/vde/vde_2x1_fifo.sv src/vde/vde_sprite_emitter.sv 
VDE_SRC += src/vde/vde_map_mem.sv src/vde/vde_sprite_mem.sv
